# Generated by Django 4.0.6 on 2022-07-13 14:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=45)),
                ('last_name', models.TextField(max_length=45)),
                ('username', models.TextField(max_length=45)),
                ('email', models.TextField(max_length=45)),
                ('password', models.TextField(max_length=45)),
                ('birthday', models.DateField()),
                ('description', models.TextField(max_length=250, null=True)),
                ('profile_photo_path', models.ImageField(blank=True, null=True)),
            ],
        ),
    ]
