# Generated by Django 4.0.6 on 2022-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('setup', models.DateTimeField()),
                ('photo_path', models.ImageField(upload_to='images/')),
                ('effect', models.CharField(blank=True, max_length=45, null=True)),
                ('like', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
    ]
